### ISSUE TITLE
Support UpdateItem

### ISSUE THREAD

**Issue by cb372** [guardian/scanamo#10]
Support for partial updates would be handy

**Comment by cb372** [comment]
Although, after thinking about it for more than 2 seconds, I'm not sure how this API would work except to basically mimic the existing Java API for UpdateItem. Not much value in doing that.

**Comment by philwills** [comment]
Looking at https://github.com/guardian/amigo/blob/master/app/data/Bakes.scala#L66 I think there's definitely significant cruft and easily typoable, tricky to discover String formats which we could do away with.

I think after #19 and #22 this is probably the next thing to try and tackle.

**Comment by philwills** [comment]
0.6.0 provides general support for this. Not every possible update is supported, but if those are a problem , we can track those as new issues.
