### ISSUE TITLE
getAll requires manual batching

### ISSUE THREAD

**Issue by philwills** [guardian/scanamo#103]
Currently `putAll` operations work around the maximum batch size limitation of DynamoDB by batching the operations behind the scenes, but inconsistently `getAll` requires the user to do the batching themselves.

`getAll` should manage the batching so that the user of the library doesn't have to worry about it.

**Comment by todor-kolev** [comment]
https://github.com/guardian/scanamo/pull/116

**Comment by philwills** [comment]
This is now out in `0.9.5`
