### ISSUE TITLE
LocalDynamoDB.client() is not working

### ISSUE THREAD

**Issue by yaboong** [guardian/scanamo#112]
What do I do to get connected to my dynamodb not local?

I made a client like below but it's still not working.. please help..

val client = AmazonDynamoDBClientBuilder.standard()
      .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("dynamodb.ap-northeast-2.amazonaws.com", "ap-northeast-2"))
      .build()

**Comment by philwills** [comment]
Responded on Gitter.
