### ISSUE TITLE
Create query with hash equals and range equals

### ISSUE THREAD

**Issue by keshav-elevio** [guardian/scanamo#113]
Hi,
   Looking for an example of creating a query with both has equals and range equals. There is one with beginsWith but not equals. Also how to add attribute expressions to query?

Thanks in advance
Keshav

**Comment by philwills** [comment]
Thanks for raising this, when I wrote the querying DSL, I didn't consider that for secondary indexes you might want to query the exact value of both hash and range, so support is missing. 

I'd welcome a PR removing this restriction, otherwise I'll try and find time to fix it.

**Comment by keshav-elevio** [comment]
Hi Phil,
   Thanks for the response. I will try to submit a PR.

K

**Comment by philwills** [comment]
This should be fixed in `0.9.5`
