### ISSUE TITLE
Incrementing and Decrementing Numeric Attributes

### ISSUE THREAD

**Issue by nemccarthy** [guardian/scanamo#114]
I want to perform a DynamoDB update operation like this  http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/WorkingWithItems.html#WorkingWithItems.AtomicCounters 
```
   // Increment an atomic counter
    const params = {
        TableName:table,
        Key:{
            "idName": idName
        },
        UpdateExpression: "set countVal = countVal + :val",
        ExpressionAttributeValues:{
            ":val":1
        },
        ReturnValues:"UPDATED_NEW"
    };
```
How do I increment & decrement attributes in Scanamo? http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.SET.IncrementAndDecrement

**Comment by philwills** [comment]
You can use `add` as part of your update query, see the `update` operation in the [Table docs](http://guardian.github.io/scanamo/latest/api/com/gu/scanamo/Table.html#update(key:com.gu.scanamo.query.UniqueKey[_],expression:com.gu.scanamo.update.UpdateExpression):com.gu.scanamo.ops.ScanamoOps[Either[com.gu.scanamo.error.DynamoReadError,V]]) for an example. Update returns the updated value.

If this doesn't get you there feel free to join the Gitter channel.
