### ISSUE TITLE
Support to send custom HTTP headers

### ISSUE THREAD

**Issue by deepakmohanakrishnan1984** [guardian/scanamo#118]
Currently the ScanamoAsync functions does not provide any option to set custom HTTP headers. It would be nice to support an equivalent function `putCustomRequestHeader` from aws-java-sdk-dynamodb.

**Comment by deepakmohanakrishnan1984** [comment]
My use case is to pass an tracing information via the headers to the underlying repository.

**Comment by philwills** [comment]
The best solution at the moment would be to use your own interpreter based on https://github.com/guardian/scanamo/blob/master/src/main/scala/com/gu/scanamo/ops/ScanamoInterpreters.scala#L67. You could then modify the `JavaRequests` object in that file to add the custom headers.

I do see that that's rather clunky though.

**Comment by deepakmohanakrishnan1984** [comment]
Thanks for our suggestions.
