### ISSUE TITLE
querying with two conditions

### ISSUE THREAD

**Issue by dollschasingmen** [guardian/scanamo#120]
Hi -- 

I would like to write a query with two equality conditions. Yet while example works:

      'mode -> "Underground" and ('line beginsWith "C")

but this does not compile:

     'mode -> "Underground" and ('line -> "C")

what is the reason behind this?

**Comment by philwills** [comment]
It's an oversight on my part. I hadn't considered that this would be necessary for indexes, as mentioned in #113. 

I'm going to close this, as I believe this is addressing the same issue as that, but feel free to reopen if you think that's mistaken.
