### ISSUE TITLE
Should LocalDynamoDB object be in src/main?

### ISSUE THREAD

**Issue by benkobalog** [guardian/scanamo#126]
The current set up doesn't match the documentation. It can't be used like that, because it's in src/test.
To me it seems like it's inteded place is be src/main.

**Comment by philwills** [comment]
It's not intended to be in src/main, as it's only a utility for testing and I don't want to risk people using it directly thinking it's talking to a real Dynamo table.

However, better documentation for what it is, including how you construct a real client, and possibly publishing the `LocalDynamoDB` in some kind of `scanamo-test` artifact are both ideas I'd support.

**Comment by benkobalog** [comment]
That makes sense. Thank you for the answer.
