### ISSUE TITLE
AWS SDK for DynamoDB should be a provided dependency?

### ISSUE THREAD

**Issue by calvinlfer** [guardian/scanamo#128]
Hey there, 

Just wondering if we should make the SDK for DynamoDB a provided dependency. I find myself doing the following in projects:
```sbt
libraryDependencies ++= {
  Seq(
    "com.gu"                  %% "scanamo"                    % "0.9.5" exclude("com.amazonaws", "aws-java-sdk-dynamodb"),
    "com.amazonaws"            % "aws-java-sdk"               % "1.11.158"
  )
}
```

The reason for doing this is usually to include other AWS libraries or for the purposes of tracking metrics on the DynamoDB client which requires other components of the SDK
```scala
AwsSdkMetrics.enableDefaultMetrics
AwsSdkMetrics.setCredentialProvider(DefaultAWSCredentialsProviderChain.getInstance)
AwsSdkMetrics.setMetricNameSpace(settings.accountsTableName.getOrElse("my-app-name"))
```

Wondering if you had any thoughts :-)

**Comment by philwills** [comment]
Not sure. Your use case seems very reasonable, but I'm slightly loathe to make the default use case any harder than necessary.

**Comment by calvinlfer** [comment]
Yeah that seems reasonable, don’t want to degrade the out of box experience.
