### ISSUE TITLE
The wrapper should be able to use filter expression in query

### ISSUE THREAD

**Issue by dakar91** [guardian/scanamo#129]
At the moment, the query operation has support only for key expression. It would be great to have add a filter expression functionality as well.

**Comment by philwills** [comment]
@dakar91 this is supported. There's an example in the [scaladoc](http://guardian.github.io/scanamo/latest/api/com/gu/scanamo/Table.html#filter[C](condition:C)(implicitevidence$3:com.gu.scanamo.query.ConditionExpression[C]):com.gu.scanamo.TableWithOptions[V]).  However, it would be good to have this documented in the main site documentation.

**Comment by philwills** [comment]
I've now opened #131 to better document this.

**Comment by philwills** [comment]
See https://guardian.github.io/scanamo/filters.html
