### ISSUE TITLE
just so you know... async doesn't really mean async

### ISSUE THREAD

**Issue by fommil** [guardian/scanamo#130]
http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/AmazonDynamoDBAsyncClient.html

"Async" you say? Oh, well, I guess that means you'll be using the NIO
HTTP clients?

https://hc.apache.org/httpcomponents-core-ga/httpcore/apidocs/org/apache/http/protocol/HttpRequestExecutor.html

Which, and I quote, "is a client side HTTP protocol handler based on the blocking (classic) I/O model."

Possible options:

- https://github.com/alessandrosimi/aws-dynamodb-nio

**Comment by rmmeans** [comment]
Yes, they have this in the documentation under: https://guardian.github.io/scanamo/asynchronous.html

What I would imagine is that once the AWS SDK 2.0 releases, Scanamo will switch to that:
https://aws.amazon.com/blogs/developer/aws-sdk-for-java-2-0-developer-preview/
https://github.com/aws/aws-sdk-java-v2

SDK 2.0 features non-blocking I/O for the async clients, and even has a pluggable HTTP layer if you want to switch out which HTTP driver the AWS SDK uses.
