### ISSUE TITLE
List scanamo in cats readme?

### ISSUE THREAD

**Issue by kailuowang** [guardian/scanamo#143]
May I list scanamo in cats readme as a related project in the cats ecosystem section? I am collecting useful libraries for new users to start applications in FP.

**Comment by philwills** [comment]
Yes, absolutely, that would be great.  Cats is absolutely key to what Scanamo does and a lot of the ideas behind it came from hanging around the Cats project, so I'd love to have Scanamo listed there.

Thanks, @kailuowang.

**Comment by kailuowang** [comment]
Thanks! @philwills. Will add to my website revamp PR.
