### ISSUE TITLE
Conditional expression `given` does not handle `and` as expected

### ISSUE THREAD

**Issue by Fruzenshtein** [guardian/scanamo#148]
When you want to write some conditional query with Scanamo you may encounter need to use `and` operator for description of more complex condition, e.g.:
```scala
table.given('id -> "item_id" and 'secret -> "item_secret")
.update(
    'id -> "item_id" and 'secret -> "item_secret", 
    set('attribute -> "important data")
)
```

But for now it does not compile, due to error:

> could not find implicit value for evidence parameter of type com.gu.scanamo.query.ConditionExpression[com.gu.scanamo.query.AndEqualsCondition[com.gu.scanamo.query.KeyEquals[String],com.gu.scanamo.query.KeyEquals[String]]]

So the solution may be:
```scala
com.gu.scanamo.query._
table.given(Condition('id -> "item_id") and 'secret -> "item_secret")
.update(
    'id -> "item_id" and 'secret -> "item_secret", 
    set('attribute -> "important data")
)
```

It works fine, but the following code does not compile, but it should:

```scala
table.given(Condition('id -> "item_id") and Condition('secret -> "item_secret"))
.update(
    'id -> "item_id" and 'secret -> "item_secret", 
    set('attribute -> "important data")
)
```

**Comment by dtboctor** [comment]
I have a question here, I'm trying to use a much more complex condition for filtering and I got it to compile, but I do see some errors of the sort 
``` com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: Value provided in ExpressionAttributeNames unused in expressions: keys: {#and_l_and_l_and_l_and_l_and_r_conditionttr, #and_l_and_r_condition, #and_l_and_l_and_l_and_r_conditionttr}```

Would this be related to this fix or potentially an error on my side?

**Comment by philwills** [comment]
@dtboctor that can't be related to the fix for this, as I haven't released it yet, but if you are able to provide more details, either in a new issue or in the [Gitter channel](https://gitter.im/guardian/scanamo), then I can dig into it.
