### ISSUE TITLE
How to get the item after a put operation?

### ISSUE THREAD

**Issue by phil79lip** [guardian/scanamo#157]
It seems scanamo is bubbling up the java type `com.amazonaws.services.dynamodbv2.model.PutItemResult`. This way one cannot access the item back from dynamo.
Any thoughts / hints to solve this?

**Comment by philwills** [comment]
There's a recently merged change (https://github.com/guardian/scanamo/pull/153) which will instead return the state before the change (if any) from a put. This isn't yet released, but should be soon. 

If you want the state after, won't that just be what you've just passed in?

**Comment by phil79lip** [comment]
Thank you @philwills. You are right. I wasn't sure the dynamoDB does nothing to the item on its own.
Your proposed PR is a nice improvement to retrieve the old state without an additional read op.
