### ISSUE TITLE
Pattern for supporting other collection types

### ISSUE THREAD

**Issue by joprice** [guardian/scanamo#26]
I attempted to define a `DynamoFormat` for scala's `Vector`, using listFormat as a template and found that the some useful helper functions (`attribute`, `javaListFormat`) are marked private. It would be convenient have access to these and avoid duplicating them in client code, or have an alternative helper for users that want to customize collection serialization.

**Comment by philwills** [comment]
I think a `Vector` instance would be a sensible addition to the core library, but yes, exposing `javaListFormat` seems reasonable.
