### ISSUE TITLE
How to limit results size when using query

### ISSUE THREAD

**Issue by kraus-as24** [guardian/scanamo#28]
Is there a way to limit the result size using `ScanamoAsync.query`?

Thanks in advance!

**Comment by philwills** [comment]
It returns a stream, which lazily pulls in page by page, so if you for instance `.take(100)`  on it, then it will only pull back the number of pages necessary to support that. 

It will always attempt to pull back a full page of results, so you might pull back a bit more data than is strictly necessary, but there shouldn't be additional requests.

**Comment by kraus-as24** [comment]
Thanks. I actually need only the first result (or the last one using a descending query) with ordering given by a range key. But as DynamoDB is supporting defining a limit on queries is it planned to add this feature? And what do you think is the difference concerning performance. Thanks.

**Comment by philwills** [comment]
It's not the near the top of my list at the moment, as my main focus with the library is to try and allow things to be done in a simple, safe way and this is currently achievable, if not optimal. Any suggestions or PRs on how it could be supported without major changes to the API would be welcome.

In terms of performance, it's very difficult to know in the abstract. I'd be a bit surprised if it was a bottleneck, but without benchmarking the particular app I wouldn't like to pretend certainty.

**Comment by adamnfish** [comment]
One concern is that in an app with a single-read-heavy workload, you'd have to over-provision your tables by `pagesize`. I wonder if exposing a way of setting the page size on the underlying DynamoDB req would give the developer the chance to optimise requests for the expected use-case?

I'll have a look through the code, see if I can work out a nice way to do it.

**Comment by philwills** [comment]
That's a good point about capacity consumption. It's now definitely on the list.

**Comment by philwills** [comment]
This is now available in 0.5.0
