### ISSUE TITLE
Examples of how to interact with new/pre-existing tables with Hash and Sort keys

### ISSUE THREAD

**Issue by referentiallytransparent** [guardian/scanamo#30]
It would be nice to have some more examples showing of this behavior :smile:

**Comment by philwills** [comment]
There's nothing particular to the examples that requires them to have new tables.

The main reason for creating and dropping tables as part of the examples is that they're all executed as test cases as part of the build pipeline.

If there's anything that's still not clear, let me know and I'll try and elaborate.

**Comment by referentiallytransparent** [comment]
I'm a bit confused as to how to use a table that has a hash and a sort key and one that has a GSI index. Can you please elaborate on this?

Thank you very much, this is an awesome library

**Comment by philwills** [comment]
The [Table scaladoc](https://guardian.github.io/scanamo/latest/api/index.html#com.gu.scanamo.Table@index(indexName:String):com.gu.scanamo.Index[V]) has an example showing querying from a GSI.

While the [Scanamo scaladoc](https://guardian.github.io/scanamo/latest/api/index.html#com.gu.scanamo.Scanamo$@get[T](client:com.amazonaws.services.dynamodbv2.AmazonDynamoDB)(tableName:String)(key:com.gu.scanamo.query.UniqueKey[_])(implicitevidence$3:com.gu.scanamo.DynamoFormat[T]):Option[cats.data.Xor[com.gu.scanamo.error.DynamoReadError,T]]) has an example of getting with a hash and range key. I should probably move the latter over to the `Table` docs now, as that's the main approach I'm suggesting.

**Comment by referentiallytransparent** [comment]
Thanks! That helps a lot :-)

**Comment by referentiallytransparent** [comment]
Oops my fat fingers

**Comment by referentiallytransparent** [comment]
I took a look at the Table example you provided. To make it more clearer that you are using a GSI, it would be great if you could state in a comment as to how the table is configured (primary key, GSI hash and sort key). What do you think?

**Comment by philwills** [comment]
Yes, I'll try and add something to the README (unless someone else gets round to a PR first).

I need to take a look at how to structure it better at some point too.

**Comment by referentiallytransparent** [comment]
Sounds good. I'm also working on a full end to end example with Play framework to get a simple REST API hooked into DynamoDB via Scanamo. You can find it here 
https://github.com/referentiallytransparent/play-framework-validation-example/tree/feature/crud/app/services/data/dynamodb

Still have to clean it up some more

**Comment by philwills** [comment]
Does https://github.com/guardian/scanamo/blob/00e4d4530acba3709e4a67c9010ea62874aaf3b0/README.md#using-indexes look like it explains things a bit more?

**Comment by referentiallytransparent** [comment]
Absolutely, great job :+1:
