### ISSUE TITLE
Filter query/scan results

### ISSUE THREAD

**Issue by dubiousdavid** [guardian/scanamo#42]
Is there a way to apply a filter to query/scan results?

**Comment by philwills** [comment]
No, there isn't. At present you'd need to filter the results that were returned from a query/scan after the query to Dynamo. 

I'd welcome a contribution which added support, but it's not something I'm actively working on.

**Comment by timchan-lumoslabs** [comment]
I was able to filter by exposing `QueryRequest`. If you want to filter, you provide your own `QueryRequest` else a new one is created, as usual. @philwills would you entertain a PR for this approach?

**Comment by philwills** [comment]
@timchan-lumoslabs my current thinking is largely towards exposing the underlying driver classes less, so it's probably not the direction I'd want to take.

If I were to try and attempt something for this, I'd be looking to see if I could do something similar to how queries/scans can be limited https://github.com/guardian/scanamo/blob/master/src/main/scala/com/gu/scanamo/Table.scala#L198

**Comment by ayoub-benali** [comment]
@philwills I am interested to see how to fix this issue but I am not sure to understand your proposal.
Do you mean adding a dynamo operator like `filter` so that you could write something like this ?

`index.query('key -> "k1" and 'range >= 100 and filter('foo beginsWith "bar"))`

**Comment by philwills** [comment]
@ayoub-benali I was thinking more something like `index.filter('foo beginsWith "bar").x.query('key -> "k1" and 'range >= 100)`, but I like you're suggested approach better, as filtering feels pretty tightly related to the querying.

**Comment by ayoub-benali** [comment]
Could you give some pointer where to start implementing something like that ?
For example would [DynamoKeyCondition.scala](https://github.com/guardian/scanamo/blob/master/src/main/scala/com/gu/scanamo/query/DynamoKeyCondition.scala) be good start ?

**Comment by philwills** [comment]
Yes, you'll need that, plus I think [QueryableKeyCondition](https://github.com/guardian/scanamo/blob/master/src/main/scala/com/gu/scanamo/query/QueryableKeyCondition.scala) and the syntax implicits inhttps://github.com/guardian/scanamo/blob/master/src/main/scala/com/gu/scanamo/package.scala#L8

**Comment by ayoub-benali** [comment]
I guess this issue can safely closed now that #102 is merged

**Comment by philwills** [comment]
This is supported as of `0.9.3`
