### ISSUE TITLE
How to get a DynamoFormat[T] from a external case class?

### ISSUE THREAD

**Issue by trbngr** [guardian/scanamo#59]
If I define a case class in the scope of my Scanamo usage, I don't have a problem.

If I import a case class from elsewhere, the compiler isn't able to find one.

Reading the code, I see `Also supports automatic derivation for case classes` in the scaladocs for `DynamoFormat[T]` and I know it works in the first scenario. I just don't know how to bring the custom format into scope.

error: `could not find implicit value for evidence parameter of type com.gu.scanamo.DynamoFormat[com.compay.readmodel.Model]`

**Comment by trbngr** [comment]
I pushed a small repro [here](https://github.com/trbngr/scanamo-demo).

I must be tired. The compiler hates that project. Type inference is totally borked. No idea 💩

**Comment by trbngr** [comment]
Turns out I just need some implicit formats for certain properties of my case classes.

ie. EntityId, ConferenceId, OffsetDateTime, etc...

**Comment by trbngr** [comment]
Just one more hurdle....how can I create a `DynamoFormat` for an `ADT`.

[see this](https://github.com/trbngr/scanamo-demo/blob/master/modules/domain/src/main/scala/com.company/States.scala)

**Comment by trbngr** [comment]
To be clear for anyone reading this in the future....

Make sure all properties in a case class have a DynamoFormat in scope. If not, you won't get any helpful errors. It will just say that there's not a format for your class.

See [this link](https://github.com/trbngr/scanamo-demo/blob/master/modules/scanamoImpl/src/main/scala/com.company/dynamodb/DynamoFormats.scala) for examples.

**Comment by philwills** [comment]
Sorry, only just noticed this. It looks pretty good to me. 

The pattern with the sealed trait seems reasonably common and is something I'd like to provide a way of deriving, to avoid all that boilerplate.

**Comment by trbngr** [comment]
Oh. I forgot about this. I actually wrote a macro for this. I will post it later

**Comment by trbngr** [comment]
Here's the macro I ended up with. Hope it helps.

https://gist.github.com/trbngr/75195f0f8fd8f5b33491b1dc22707249

**Comment by drocsid** [comment]
I had been building my own local scanamo 6.1-SNAPSHOT locally with https://github.com/guardian/scanamo/issues/55 applied. I had been using a simple case class with a derived format created by scanamo-scrooge, like case class AFormatWrapper(rowkey: Array[Byte],det: AFormat) . Now updating to scanamo 7 and getting: 

could not find implicit value for evidence parameter of type com.gu.scanamo.DynamoFormat[com.example.AFormatWrapper]

I think I'm facing the same issue. @philwills  this seems to be a related issue. Any suggestions?
