### ISSUE TITLE
Support UpdateItemRequest.withReturnValues

### ISSUE THREAD

**Issue by cb372** [guardian/scanamo#61]
When updating an item, it's possible to specify the values you want returned:
- `NONE` (default)
- `ALL_OLD`
- `UPDATED_OLD`
- `ALL_NEW`
- `UPDATED_NEW`

I need access to the updated value [here](https://github.com/guardian/amigo/blob/7e3670558b51d23eeb7a71efa628331e6d7e78ee/app/data/Recipes.scala#L71), but Scanamo doesn't currently support this.

I can have a go at a PR, but I'm not sure whether to just add an argument (with a default param) to `Table.update` or to try and add something to the query DSL. I don't see any other default args in the Scanamo API; I'm not sure how @philwills feels about them.

**Comment by philwills** [comment]
Fixed by #66
