### ISSUE TITLE
How do you build a dynamic update query?

### ISSUE THREAD

**Issue by calvinlfer** [guardian/scanamo#68]
Hello everyone,

I was wondering how to build a dynamic update instruction as I have a use case where I want to update one or more fields in DynamoDB and did not find a clean way. 

I have an update coming in that looks like this:
```scala
case class IncomingUpdate(firstName: Option[String], xCurrency: Option[Int], yCurrency: Option[Int])
```

Not all fields could be present and these map onto DynamoDB. I was wondering how you could build an update query in a nice manner.

I detailed my attempts at trying to come up with something over here but alas with no luck:
https://gitter.im/guardian/scanamo?at=57bdd2bb5bdd197c1cb9e405

**Comment by philwills** [comment]
Thanks for raising the issue @calvinlfer. It's definitely something I want to make possible, but I've yet to find a good solution. Having this here will make it easier for me to ask for help.
