### ISSUE TITLE
Add option for consistent read on Get operation

### ISSUE THREAD

**Issue by amherrington13** [guardian/scanamo#72]
In using scanamo the past few months, I came across an opportunity for a possible feature addition. My team currently has a need to do a consistent read on a Get operation from DynamoDB. Is this option a feature that could be added/accepted into the scanamo library? 

I've put together a PR that is my first pass at adding this in for a Get operation. The idea is that the consistent read option would default to false, causing it to work as it does today, but a user could optionally pass in a value of true if a consistent read was needed. 

Feedback and/or suggestions are welcome! Thanks!

**Comment by philwills** [comment]
Support for consistent Get/Scan/Query is out as 0.8.3. Please let me know how you get on.
