### ISSUE TITLE
moreHelpfulErrorMessage sometimes not so helpful

### ISSUE THREAD

**Issue by travisbrown** [guardian/scanamo#76]
Just ran into this in the wild—if a higher priority instance fails but a lower priority one doesn't, there's still a message that looks like a compilation failure:

```scala
scala> import com.gu.scanamo.DynamoFormat
import com.gu.scanamo.DynamoFormat

scala> class Foo(x: Int); class Bar(y: Int)
defined class Foo
defined class Bar

scala> trait Low { implicit val fooFormat: DynamoFormat[Foo] = ??? }
defined trait Low

scala> object High extends Low {
     |   implicit def anotherFooFormat(implicit bf: DynamoFormat[Bar]): DynamoFormat[Foo] = ???
     | }
defined object High

scala> import High._
import High._

scala> def getFooFormat = DynamoFormat[Foo]
<console>:19: could not find implicit value for parameter instance: com.gu.scanamo.DynamoFormat[Bar]
       def getFooFormat = DynamoFormat[Foo]
                                      ^
getFooFormat: com.gu.scanamo.DynamoFormat[Foo]
```

This can be pretty confusing when you're scrolling through a bunch of compilation errors and a few are actually `[info]` and not errors at all.

**Comment by philwills** [comment]
Sorry, only just saw this. 

That's a shame.  I'd be sad to lose something along these lines, but I'd rather not have it than have it have the potential for confusion like this.  Will try and have a play and see if I can find something more reliable.

**Comment by philwills** [comment]
Hopefully, I'll work out a way of achieving the original goal without this issue in the future, but for the moment, I'm going to close this, as at least there's nothing misleading in 0.9.0
