### ISSUE TITLE
Lack of documentation for conditional expressions on put and delete

### ISSUE THREAD

**Issue by sihil** [guardian/scanamo#92]
The code is definitely there (e.g. PR #31), but I have not yet figured out how to use it. Some documentation would be great, or at the very least a brief example on the PR or in a test.

**Comment by philwills** [comment]
http://guardian.github.io/scanamo/latest/api/com/gu/scanamo/Table.html#given[T](condition:T)(implicitevidence$2:com.gu.scanamo.query.ConditionExpression[T]):com.gu.scanamo.query.ConditionalOperation[V,T] has some examples. 

Would be good to add to the main docs though.

**Comment by sihil** [comment]
Ah - that's the piece I was missing. Yes - having a section on the main docs would help.

**Comment by philwills** [comment]
Closing, as this is now published (https://guardian.github.io/scanamo/conditional-operations.html), though suggestions or PRs to improve are always welcome.

**Comment by sydneyos** [comment]
Neither of these links work ):

**Comment by davidfurey** [comment]
@sydneyos - The conditional operations doc is now available at https://www.scanamo.org/conditional-operations.html

@regiskuckaertz - sbt-unidoc was removed quite a while ago (https://github.com/scanamo/scanamo/pull/567/commits/80d624e8ac7ddf6ab211758614d8dec36411d1a2).  If there is no intention to bring it back, we should remove the API link from the microsite by removing [`micrositeDocumentationUrl ` and `micrositeDocumentationLabelDescription ` in `build.sbt`](https://github.com/scanamo/scanamo/blob/master/build.sbt#L296-L297)
